name: Pixel 8a Auto Patch (Magisk Alpha)

on:
  workflow_dispatch:
    inputs:
      factory_url:
        description: "Direct Factory Image URL"
        required: true

jobs:
  patch:
    runs-on: ubuntu-22.04

    steps:

      # ==========================
      # FREE SPACE
      # ==========================
      - name: Free Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          df -h

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y wget unzip zip python3 cpio

      # ==========================
      # DOWNLOAD FACTORY
      # ==========================
      - name: Download Factory
        run: |
          wget -O factory.zip "${{ github.event.inputs.factory_url }}"
          unzip factory.zip
          cd akita-*
          unzip image-*.zip
          mv boot.img ../../boot.img

      # ==========================
      # DOWNLOAD MAGISK ALPHA
      # ==========================
      - name: Download Magisk Alpha
        run: |
          # Get latest release download URL automatically
          MAGISK_URL=$(curl -s https://api.github.com/repos/vvb2060/Magisk/releases/latest \
            | grep browser_download_url \
            | grep ".apk" \
            | cut -d '"' -f 4)

          echo "Downloading $MAGISK_URL"
          wget -O magisk.apk "$MAGISK_URL"

          unzip magisk.apk lib/arm64-v8a/libmagiskboot.so -d magisk
          mv magisk/lib/arm64-v8a/libmagiskboot.so magiskboot
          chmod +x magiskboot

      # ==========================
      # PATCH BOOT
      # ==========================
      - name: Patch Boot
        run: |
          ./magiskboot unpack boot.img
          ./magiskboot repack boot.img
          mv new-boot.img magisk_patched.img

      # ==========================
      # UPLOAD ARTIFACT
      # ==========================
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Pixel8a-MagiskAlpha-Patched
          path: magisk_patched.img
